name: php-tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.3]
        laravel: [10.*, 11.*]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, bcmath, pdo_sqlite
          coverage: none
          
      - name: Allow Pest plugin
        run: composer config --no-plugins allow-plugins.pestphp/pest-plugin true

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Configure SQLite database
        run: |
          touch database/database.sqlite
          php artisan migrate --force

      - name: Clear caches
        run: php artisan config:clear && php artisan cache:clear && php artisan route:clear

      - name: Run Tests
        run: php artisan test
